# Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# General information about the project.
project = 'Triton Ascend'
copyright = '2025, Huawei'
author = 'Huawei'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = ''
# The full version, including alpha/beta/rc tags.
release = ''

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.autosummary',
    'sphinx.ext.coverage',
    'sphinx.ext.napoleon',
    'sphinx.ext.autosectionlabel',
    'myst_parser',
]

autosummary_generate = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh'

# The name of the Pygments (syntax highlighting) style to use
pygments_style = 'sphinx'

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_rtd_theme"

html_theme_options = {}

html_static_path = ["_static"]

html_css_files = [
    "custom.css",
]

import os as _os
import sys as _sys
import importlib.util as _ilu

_HERE = _os.path.dirname(__file__)
_REPO = _os.path.abspath(_os.path.join(_HERE, "..", ".."))


def _load_module(module_name, file_path):
    """Load a Python module by file path (used for dirs with hyphens or
    when the parent package isn't on sys.path)."""
    spec = _ilu.spec_from_file_location(module_name, file_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load {module_name!r} from {file_path!r}")
    module = _ilu.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# Only inject stubs for C extensions when triton isn't actually importable
# (e.g. RTD builds without CANN).  In a real dev env we prefer the actual
# triton install so the generated docs match runtime behaviour.
# TRITON_DOCS_FORCE_MOCK=1 skips the real import entirely; RTD always forces
# the mock so its builds never depend on a half-working triton install.
_sys.path.insert(0, _os.path.join(_REPO, "python"))
_force_mock = (_os.environ.get("TRITON_DOCS_FORCE_MOCK", "").lower() in ("1", "true", "yes")
               or _os.environ.get("READTHEDOCS") == "True")
if not _force_mock:
    try:
        # Broken installs fail in many ways beyond ImportError (RuntimeError
        # from backend discovery, FileNotFoundError from compiler probes...);
        # any failure means we fall back to the mock.
        import triton  # noqa: F401,E402
    except Exception as _exc:
        print(f"import triton failed ({_exc!r}); building docs with mock stubs")
        _force_mock = True

if _force_mock:
    _load_module(
        "docs.zh._mock._triton_mock",
        _os.path.join(_HERE, "_mock", "_triton_mock.py"),
    ).install()

import triton  # noqa: E402
import triton.language.extra as _tl_extra  # noqa: E402

# Extend the extra package path so triton.language.extra.cann is importable.
_cann_lang_path = _os.path.join(_REPO, "third_party", "ascend", "language")
if _cann_lang_path not in _tl_extra.__path__:
    _tl_extra.__path__.append(_cann_lang_path)

import sphinx.ext.autosummary  # noqa: E402
import sphinx.util.inspect  # noqa: E402


# JITFunction unwrap patch (from upstream triton v3.5.0 docs/conf.py):
# autodoc must look at the wrapped Python function, not the JITFunction object.
def _unwrap_jit(fn):
    """Wrap a Sphinx inspection helper so it sees JITFunction.fn instead."""

    def wrapper(obj, **kwargs):
        if isinstance(obj, triton.runtime.JITFunction):
            obj = obj.fn
        return fn(obj, **kwargs)

    return wrapper


# get_documenter was removed in Sphinx 9; guard accordingly.
if hasattr(sphinx.ext.autosummary, "get_documenter"):
    _orig_get_documenter = sphinx.ext.autosummary.get_documenter

    def _get_documenter(app, obj, parent):
        if isinstance(obj, triton.runtime.JITFunction):
            obj = obj.fn
        return _orig_get_documenter(app, obj, parent)

    sphinx.ext.autosummary.get_documenter = _get_documenter

sphinx.util.inspect.unwrap_all = _unwrap_jit(sphinx.util.inspect.unwrap_all)
sphinx.util.inspect.signature = _unwrap_jit(sphinx.util.inspect.signature)
sphinx.util.inspect.object_description = _unwrap_jit(sphinx.util.inspect.object_description)


def setup(app):
    """Register custom Sphinx extensions."""
    _load_module(
        "docs.zh.python_api._inject_ascend_notes",
        _os.path.join(_HERE, "python-api", "_inject_ascend_notes.py"),
    ).setup(app)
