name: Documentation
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  Build-Documentation:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    env:
      PYTHON: "python3"

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Clear docs
        run: rm -rf /tmp/triton-docs
        continue-on-error: true

      - name: Install dependent packages
        run: make docs-requirements

      - name: Build docs
        run: MAX_JOBS=4 make docs-only

      - name: Update docs
        run: |
          mkdir /tmp/triton-docs/
          mv docs/_build/html/* /tmp/triton-docs/
          git checkout gh-pages
          cp -r index.html /tmp/triton-docs/
          cp -r .nojekyll /tmp/triton-docs/
          rm -rf *
          cp -r /tmp/triton-docs/* .
          git add .
          git config --global user.email "N/A"
          git config --global user.name "gh-actions-bot"
          git commit -am "[GH-PAGES] Updated website"

      - name: Publish docs
        run: git push origin gh-pages
